version: "3"

services:
    
    registry-container:
        build: 
          context: .
          dockerfile: Dockerfile
        
        ports:
            - "5000:5000"
        
        restart: always
        
        volumes:
          - /var:/var/lib/

        network:
          minharede:
            driver: bridge
